@AestusDemoAPI_HostAddress = http://localhost:5019

GET {{AestusDemoAPI_HostAddress}}/anomalies/
Accept: application/json

###
POST {{AestusDemoAPI_HostAddress}}/transactions/
Accept: application/json


{
  "user_id": "abc123",
  "amount": 74.23,
  "timestamp": "2024-04-24T12:43:00Z",
  "location": "Hum na Sutli"
}

###
