// <auto-generated />
using System;
using AestusDemoAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AestusDemoAPI.Infrastructure.Migrations
{
    [DbContext(typeof(FinTechAestusContext))]
    [Migration("20250703124035_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AestusDemoAPI.Domain.Entitites.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50.0,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 0, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 49.5,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 5, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5000.0,
                            Comment = "Neuobičajeno visok iznos + neočekivana lokacija",
                            IsSuspicious = true,
                            Location = "Ljubljana",
                            Timestamp = new DateTime(2024, 4, 24, 11, 7, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 48.0,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 20, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 47.990000000000002,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 30, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 4000.0,
                            Comment = "Neuobičajeno visok iznos",
                            IsSuspicious = true,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 32, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50.100000000000001,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 40, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 52.0,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 50, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 51.0,
                            Comment = "Normalna potrošnja",
                            IsSuspicious = false,
                            Location = "Zagreb",
                            Timestamp = new DateTime(2024, 4, 24, 11, 55, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 49.990000000000002,
                            Comment = "Neočekivana lokacija",
                            IsSuspicious = true,
                            Location = "Beograd",
                            Timestamp = new DateTime(2024, 4, 24, 12, 0, 0, 0, DateTimeKind.Local),
                            UserId = "user_001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
